algoritmo "Entrada e saíde de dados"
// Função :
// Autor :
// Data : 04/04/2021
// Descrição: Entrada e saíde de dados
var
   nome: caractere
   nota: inteiro
inicio
// Seção de Comandos 
   Escreval ("Digite o seu nome: ")
   Leia (nome)
   
   Escreval ("Digite a sua idade: ")
   Leia (nota)
   
   Escreval("O nome digitado foi: ",nome)
   Escreval ("A idade digitada foi: ",nota)
   
fimalgoritmo

