algoritmo "estrutura-para-faca"
// Função :
// Autor :
// Data : 08/04/2021
// Seção de Declarações 
var
    numero, fatorial, contador: inteiro
inicio
// Seção de Comandos
   escreval ("Digite o número para calcular o fatorial: ")
   Leia (numero)
   fatorial := 1
   para contador de 1 ate numero faca
        fatorial := fatorial * contador
   fimpara
   Escreval ("O fatorial de ", numero,  " é: ", fatorial)
   
fimalgoritmo

